#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Ref-Util
Version  : 0.204
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/A/AR/ARC/Ref-Util-0.204.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/A/AR/ARC/Ref-Util-0.204.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libr/libref-util-perl/libref-util-perl_0.204-1.debian.tar.xz
Summary  : 'Utility functions for checking references'
Group    : Development/Tools
License  : MIT
Requires: perl-Ref-Util-license
Requires: perl-Ref-Util-man
Requires: perl(Ref::Util::XS)
BuildRequires : perl(Ref::Util::XS)

%description
This archive contains the distribution Ref-Util,
version 0.204:
Utility functions for checking references

%package license
Summary: license components for the perl-Ref-Util package.
Group: Default

%description license
license components for the perl-Ref-Util package.


%package man
Summary: man components for the perl-Ref-Util package.
Group: Default

%description man
man components for the perl-Ref-Util package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Ref-Util-0.204
mkdir -p %{_topdir}/BUILD/Ref-Util-0.204/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Ref-Util-0.204/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Ref-Util
cp LICENSE %{buildroot}/usr/share/doc/perl-Ref-Util/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Ref/Util.pm
/usr/lib/perl5/site_perl/5.26.1/Ref/Util/PP.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Ref-Util/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Ref::Util.3
/usr/share/man/man3/Ref::Util::PP.3
